### ISSUE TITLE
Meld process OK, but no variant in viewer

### ISSUE THREAD

**Issue by gregbeast** [facebookincubator/glTFVariantMeld#32]
Hi team,

great tool and really easy to setup on Mac.
Melt files is working fine but nothing shown or functional in viewer https://github.khronos.org/glTF-Sample-Viewer-Release/

<img width="890" alt="BuggyResult_TestVariation_Variant_03" src="https://user-images.githubusercontent.com/9369666/116990183-0eb8c880-acd3-11eb-8df2-7c500fcac635.png">
<img width="913" alt="BuggyResult_TestVariation_Variant_02" src="https://user-images.githubusercontent.com/9369666/116990189-10828c00-acd3-11eb-9e30-53bbbc0e7aea.png">
<img width="905" alt="BuggyResult_TestVariation_Variant_01" src="https://user-images.githubusercontent.com/9369666/116990192-111b2280-acd3-11eb-96d6-59a71770efc8.png">
<img width="934" alt="Model_Used_For_Variant_03" src="https://user-images.githubusercontent.com/9369666/116990195-11b3b900-acd3-11eb-9453-c53fb39bf56d.png">
<img width="904" alt="Model_Used_For_Variant_02" src="https://user-images.githubusercontent.com/9369666/116990197-124c4f80-acd3-11eb-9df8-fe75b765d1a3.png">
<img width="907" alt="Model_Used_For_Variant_01" src="https://user-images.githubusercontent.com/9369666/116990200-12e4e600-acd3-11eb-830e-108952323cf9.png">

Some ideas? Sources files following:

[Test-GLB-variants.zip](https://github.com/facebookincubator/glTFVariantMeld/files/6420356/Test-GLB-variants.zip)

Update 01 : Fix by hands. After reconvert GLB generated by glTFVariantMeld in glTF, I have seen used tag was "mapping". But the required tag is "mappings". Possible to fix it in your app.js ?

**Comment by mixtive** [comment]
How did you fix it by hand, and did it then show up in model-viewer?

**Comment by ValentinGerhard** [comment]
I have the same problem... where in the code is the tag "mapping" defined? I can't find it.

**Comment by BrandonHyder** [comment]
I have the same issue as well, currently trying to find this
